pipeline {
   agent any
   stages  {
      stage ('helloworld') {
          steps {
                  echo 'Hello World'
                  echo 'What is your name?'
              }
        } 
    }
  }        
