pipeline {
   agent any
   stages ("hello") {
      stage ("helloworld") {
          steps {
                  echo "Hello World 2020 03 12"  
                  echo "what is your name"
              }
        } 
    }
  }        
