pipeline {
   agent any
   stages  {
      stage ('helloworld') {
          steps {
                  echo 'Hello World 2020'
                  echo 'what is your name'
              }
        } 
    }
  }        
